#!/bin/bash
cd ..
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=3 --shape=2"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=3 --shape=4"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=4 --shape=2"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=4 --shape=4"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=5 --shape=2"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=5 --shape=4"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=6 --shape=2"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=6 --shape=4"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=7 --shape=2"
./waf --run "red-vs-ared --queueDiscType=ARED --redMinTh=7 --shape=4"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=3 --shape=2"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=3 --shape=4"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=4 --shape=2"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=4 --shape=4"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=5 --shape=2"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=5 --shape=4"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=6 --shape=2"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=6 --shape=4"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=7 --shape=2"
./waf --run "red-vs-ared --queueDiscType=RED --redMinTh=7 --shape=4"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=3 --shape=2"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=3 --shape=4"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=4 --shape=2"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=4 --shape=4"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=5 --shape=2"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=5 --shape=4"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=6 --shape=2"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=6 --shape=4"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=7 --shape=2"
./waf --run "red-vs-hred --queueDiscType=HRED --redMinTh=7 --shape=4"
cd automation

